name: Deploy Lambda Function
on:
 push:
  branches: [ test ]
  
 pull_request:
  branches: [ test ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v3
         
       - name: ZIP FILES
         run: |
            cd demo/ 
            pwd
            zip -r9 check.zip first.py
            pwd
  
  
     
