name: checking zipping functionality
on:
 push:
  branches: [ demo ]
  
 pull_request:
  branches: [ demo ]

jobs:
 deploy:
    runs-on: ubuntu-latest
   
    permissions:
      id-token: write
      contents: read
    defaults:
       run:
        shell: bash
    steps:
    
    
       - name: Checkout
         uses: actions/checkout@v3
         
       - name: unzip file
         run: |
           cd dir/
           
           unzip ../testzip.zip -d dir

