##
name: Deploy Lambda Function
on:
 push:
  branches: [ test ]
  
 pull_request:
  branches: [ test ]

jobs:
 deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        shell: bash
    steps:
    
    
       - name: Checkout
         uses: actions/checkout@v3
        
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
          role-to-assume: ${{ secrets.AWS_ROLE }}  
          aws-region: ${{ secrets.AWS_REGION }} 
         
       - name: ZIP FILES
         run: |
            cd demo/ 
            zip -r9 check.zip first.py
            pwd
       - name : Upload artifact
         uses: actions/upload-artifact@v1
         with: 
            name : testzip
            path : demo
            
       - name : AWS Deploy
         run: |
          aws lambda update-function-code --function-name lambda-github-function --zip-file fileb://check.zip
          
  
     
